import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App123", // 모든 경로에 적용
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <Link href="/">[Home], </Link>
          <Link href="/about">[About], </Link>
          <Link href="/blog">[Blog],</Link>
          <Link href="/contact">[Contact],</Link>
          <Link href="/business">[Business],</Link>
          <Link href="/test">[TestPage],</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
